name: CI

on:
  push:
    paths-ignore:
      - '**.md'
      - '.codex/**'
  pull_request:
    paths-ignore:
      - '**.md'
      - '.codex/**'
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: ShellCheck
        uses: ludeeus/action-shellcheck@v2
        with:
          scandir: .
          severity: style

      - name: Setup shfmt
        uses: mfinelli/setup-shfmt@v2

      - name: Format check (shfmt)
        run: shfmt -i 2 -ci -d typing.sh

  test:
    runs-on: ubuntu-latest
    needs: lint
    timeout-minutes: 15
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install bats
        run: |
          sudo apt-get update
          sudo apt-get install -y bats

      - name: Run bats tests
        run: bats --print-output-on-failure -r tests
