name: CI

on:
  push:
  pull_request:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install tooling (shellcheck, shfmt)
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck shfmt

      - name: Lint
        run: make lint

      - name: Tests (Docker + Bats)
        run: ./scripts/test-docker.sh -r tests
