name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install shellcheck
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
      - name: Run shellcheck
        run: shellcheck typing.sh

  fmt-check:
    name: fmt-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install shfmt
        run: |
          sudo apt-get update
          sudo apt-get install -y shfmt
      - name: Check formatting (shfmt -d)
        run: shfmt -i 2 -ci -d typing.sh

  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run Bats tests (Docker)
        run: |
          chmod +x scripts/test-docker.sh
          ./scripts/test-docker.sh -r tests

